---
title: "Untitled"
author: "jhlee"
output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rstatix)  # p-value plotting
library(stringr)
library(ggplot2)
library(ggpubr)
library(ggsci)    # ggplot palettes
library(ggbeeswarm)

# ggplot color palette 
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbbPalette <- c("#56B4E9", "#CC79A7", "#0072B2", "#009E73")
gbPalette <- c("#999999", "#0072B2")
grPalette <- c("#999999", "#BF2126")

```

# Set path for data and load data
```{r set paths}
setwd("/home/jhlee4991/Github/project_stressSD")

PATH_ROOT = '/home/jhlee4991/Github/project_stressSD/'
PATH_DATA = '/home/jhlee4991/Github/project_stressSD/bayesian_modeling/data/'

tmp_data <- list.files(PATH_DATA, pattern = "*.txt")
df_raw <- read.table(paste0(PATH_DATA, tmp_data[1]), head = T, sep = "\t")
df_behav <- df_raw
df_behav$totalFairseq <- gsub(1, "targetSame", df_behav$totalFairseq)
df_behav$totalFairseq <- gsub(0, "targetMore", df_behav$totalFairseq)
```

```{r}
df_behav %>% 
  mutate(gain = ifelse(choice == 1, amount_default, amount_self)) %>% 
  mutate(social_distance = factor(social_distance, levels = c(1, 5, 10, 20, 50, 100))) %>% 
  group_by(subjID, social_distance, totalFairseq) %>% 
  summarise(gain = mean(gain)) %>% 
  ggplot(aes(x = social_distance, y = gain, fill = social_distance))+
  facet_wrap(~ totalFairseq, 
             labeller = as_labeller(c("targetMore" = "Target More",
                                      "targetSame" = "Target Same"))) + 
  stat_summary(geom = "bar", fun = mean, size = 0.75) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.3, size = 0.75) +
  scale_fill_viridis(discrete = TRUE) +
  xlab('Social Distance') +
  ylab('Estimated Self gain') +
  theme_bw() + 
  theme(legend.position = 'none',
        # legend.title = 'Social Distance',
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.spacing = unit(1, 'pt'),
        strip.background = element_blank())
  theme_bw()+
  scale_fill_startrek()

```

